apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: model-server
build:
  artifacts:
    - image: europe-west2-docker.pkg.dev/gareths-project/main/model-server
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/model.yaml
    - k8s/ingress.yaml
    - k8s/service.yaml
