name: Deploy model
run-name: ${{ github.actor }} is deploying
on: [push]
# on:
#   push:
#     branches:
#     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "github-action@gareths-project.iam.gserviceaccount.com"
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - uses: "google-github-actions/setup-gcloud@v1"
        with:
          install_components: gke-gcloud-auth-plugin

      - run: gcloud container clusters get-credentials gareths-project-cluster --zone europe-west4-a
      - run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build and deploy
        uses: hiberbee/github-action-skaffold@1.25.0
        with:
          command: build
          working-directory: ./model_server
          repository: europe-west2-docker.pkg.dev/gareths-project
          tag: ${{ github.sha }}
